In [6]:
'''Q1. Missing Data Identification

Scenario:
 The hospital suspects incomplete patient records.

Task:

Identify missing values in each column

Calculate percentage of missing data
'''

import pandas as pd
df = pd.read_csv("healthcare_data_cleaning_dataset.csv")
df.isnull().sum()

Patient_ID              0
Age                   600
Gender                  0
City                    0
Diagnosis               0
Hospital_Visits         0
Treatment_Cost        593
Insurance_Coverage      0
Admission_Date          0
dtype: int64

In [ ]:
(df.isnull().sum()/len(df))*100

In [ ]:
'''Q2. Handling Missing Age

Scenario:
 Age is critical for medical analysis, but some values are missing.

Task:

Replace missing Age values with an appropriate method

Justify your choice (mean/median)
'''
df["Age"].mean()

In [7]:
df["Age"]= df["Age"].fillna(df["Age"].mean())
df

,Patient_ID,Age,Gender,City,Diagnosis,Hospital_Visits,Treatment_Cost,Insurance_Coverage,Admission_Date
0,17270,35.000000,Male,Bangalore,Hypertension,13,41010.0,1,2023-11-30
1,10860,21.000000,Female,Hyderabad,Flu,11,12194.0,1,2023-02-23
2,15390,77.000000,Female,Bangalore,Asthma,2,45086.0,0,2023-03-14
3,15191,79.000000,Female,Mumbai,Asthma,13,40842.0,0,2023-08-01
4,15734,60.000000,Female,Delhi,Asthma,1,9873.0,1,2023-06-20
...,...,...,...,...,...,...,...,...,...
5095,11764,49.597556,Female,Mumbai,COVID-19,15,NaN,0,2023-09-22
5096,17597,49.597556,Female,Chennai,Asthma,2,NaN,0,2023-06-26
5097,19171,49.597556,Female,Mumbai,Flu,1,NaN,1,2023-12-31
5098,13854,49.597556,Female,Bangalore,Flu,17,NaN,0,2023-01-18
5099,14859,49.597556,Male,Delhi,Hypertension,19,NaN,0,2023-08-28

'''Q2(2)Justification: Mean imputation is appropriate for Age when the age values are reasonably distributed and do not contain extreme outliers. It replaces missing values with the average age while keeping the dataset size unchanged.
'''

In [ ]:
'''Q3. Handling Missing Treatment Cost

Scenario:
 Treatment cost is highly skewed due to expensive treatments.

Task:

Handle missing Treatment_Cost values

Choose the correct imputation method and explain why
'''

In [8]:
df["Treatment_Cost"]=df["Treatment_Cost"].fillna(df["Treatment_Cost"].median())
df

,Patient_ID,Age,Gender,City,Diagnosis,Hospital_Visits,Treatment_Cost,Insurance_Coverage,Admission_Date
0,17270,35.000000,Male,Bangalore,Hypertension,13,41010.0,1,2023-11-30
1,10860,21.000000,Female,Hyderabad,Flu,11,12194.0,1,2023-02-23
2,15390,77.000000,Female,Bangalore,Asthma,2,45086.0,0,2023-03-14
3,15191,79.000000,Female,Mumbai,Asthma,13,40842.0,0,2023-08-01
4,15734,60.000000,Female,Delhi,Asthma,1,9873.0,1,2023-06-20
...,...,...,...,...,...,...,...,...,...
5095,11764,49.597556,Female,Mumbai,COVID-19,15,24797.0,0,2023-09-22
5096,17597,49.597556,Female,Chennai,Asthma,2,24797.0,0,2023-06-26
5097,19171,49.597556,Female,Mumbai,Flu,1,24797.0,1,2023-12-31
5098,13854,49.597556,Female,Bangalore,Flu,17,24797.0,0,2023-01-18
5099,14859,49.597556,Male,Delhi,Hypertension,19,24797.0,0,2023-08-28

Q3(2)-Treatment_Cost is highly skewed and contains extreme values. Therefore, median imputation was used because the median is less affected by extreme values than the mean.

In [9]:
'''4. Duplicate Patient Records

Scenario:
 Some patient records were entered multiple times.

Task:

Identify duplicate rows

Remove duplicates

Compare dataset size before and after
'''

before = len(df)
before

5100

In [10]:
df=pd.read_csv("healthcare_data_cleaning_dataset.csv")

In [11]:
#Q4(1)
df[df.duplicated(keep=False)]

,Patient_ID,Age,Gender,City,Diagnosis,Hospital_Visits,Treatment_Cost,Insurance_Coverage,Admission_Date
23,12558,NaN,Male,Chennai,Flu,9,NaN,0,2023-03-27
29,10189,NaN,Male,Delhi,Diabetes,8,NaN,0,2023-08-18
65,14297,NaN,Male,Mumbai,Diabetes,9,NaN,1,2023-10-13
79,14859,NaN,Male,Delhi,Hypertension,19,NaN,0,2023-08-28
84,15276,NaN,Male,Delhi,Hypertension,3,NaN,1,2023-01-11
...,...,...,...,...,...,...,...,...,...
5094,11571,NaN,Female,Chennai,COVID-19,4,NaN,0,2023-01-28
5096,17597,NaN,Female,Chennai,Asthma,2,NaN,0,2023-06-26
5097,19171,NaN,Female,Mumbai,Flu,1,NaN,1,2023-12-31
5098,13854,NaN,Female,Bangalore,Flu,17,NaN,0,2023-01-18
5099,14859,NaN,Male,Delhi,Hypertension,19,NaN,0,2023-08-28

In [12]:
# Q4(2)
df = df.drop_duplicates()
df

,Patient_ID,Age,Gender,City,Diagnosis,Hospital_Visits,Treatment_Cost,Insurance_Coverage,Admission_Date
0,17270,35.0,Male,Bangalore,Hypertension,13,41010.0,1,2023-11-30
1,10860,21.0,Female,Hyderabad,Flu,11,12194.0,1,2023-02-23
2,15390,77.0,Female,Bangalore,Asthma,2,45086.0,0,2023-03-14
3,15191,79.0,Female,Mumbai,Asthma,13,40842.0,0,2023-08-01
4,15734,60.0,Female,Delhi,Asthma,1,9873.0,1,2023-06-20
...,...,...,...,...,...,...,...,...,...
4996,16135,NaN,Female,Delhi,Hypertension,13,NaN,1,2023-11-02
4997,15573,35.0,Female,Delhi,COVID-19,19,2585.0,1,2023-12-02
4998,14131,60.0,Female,Chennai,Hypertension,4,31337.0,0,2023-04-07
4999,19900,16.0,Female,Chennai,Flu,16,39801.0,0,2023-08-04
5095,11764,NaN,Female,Mumbai,COVID-19,15,NaN,0,2023-09-22

In [13]:
after=len(df)
after

5001

In [14]:
#Q4(3)
print("Before:", before)
print("After:", after)
print("Duplicate rows removed:", before - after)

Before: 5100
After: 5001
Duplicate rows removed: 99

In [15]:
'''Q5. Invalid Age Values (Data Quality Check)

Scenario:
 Some patients have unrealistic age values (e.g., >100 or <0).

Task:

Detect such records

Decide whether to remove or correct them
'''
#Q5(1)
df[(df["Age"]>100) | (df["Age"]<0)]

Empty DataFrame
Columns: [Patient_ID, Age, Gender, City, Diagnosis, Hospital_Visits, Treatment_Cost, Insurance_Coverage, Admission_Date]
Index: []

In [16]:
((df["Age"] > 100) | (df["Age"] < 0)).sum()

np.int64(0)

Q5(2)-No unrealistic Age values were found. All Age values are within the acceptable range of 0–100, so no records need to be removed or corrected.

In [17]:
'''Q6. Outlier Detection (Treatment Cost)

Scenario:
 Extreme treatment costs are affecting analysis.

Task:

Detect outliers using IQR method

Display number of outliers
'''
#Q6(1)
q1=df["Treatment_Cost"].quantile(0.25)
q1
q3=df["Treatment_Cost"].quantile(0.75)
q3
IQR = q3-q1
IQR
lower_limit = q1-1.5*IQR
upper_limit = q3+1.5*IQR
outlier = df[(df["Treatment_Cost"]<lower_limit)|(df["Treatment_Cost"]>upper_limit)]
outlier

,Patient_ID,Age,Gender,City,Diagnosis,Hospital_Visits,Treatment_Cost,Insurance_Coverage,Admission_Date
53,13152,91.0,Female,Chennai,COVID-19,13,199702.965333,0,2023-01-24
86,10064,28.0,Female,Hyderabad,Hypertension,16,199702.965333,0,2023-02-18
124,17035,59.0,Male,Delhi,Flu,9,199702.965333,0,2023-04-27
183,15855,36.0,Male,Mumbai,Diabetes,1,199702.965333,0,2023-01-16
215,19561,29.0,Male,Mumbai,Flu,16,199702.965333,0,2023-05-31
332,11686,51.0,Male,Delhi,Asthma,16,199702.965333,1,2023-03-31
382,10876,58.0,Female,Bangalore,Hypertension,1,199702.965333,1,2023-10-21
416,14070,NaN,Male,Hyderabad,Flu,6,199702.965333,0,2023-08-18
452,10851,42.0,Female,Bangalore,COVID-19,15,199702.965333,0,2023-06-27
796,18150,37.0,Female,Bangalore,Flu,17,199702.965333,0,2023-03-26
833,19361,41.0,Female,Delhi,Diabetes,19,199702.965333,0,2023-10-08
1127,10943,26.0,Female,Delhi,Asthma,19,199702.965333,0,2023-06-02
1176,18232,29.0,Male,Chennai,Diabetes,10,199702.965333,1,2023-07-10
1219,15408,44.0,Male,Delhi,Hypertension,10,199702.965333,0,2023-04-14
1392,14876,70.0,Male,Mumbai,Diabetes,11,199702.965333,1,2023-12-27
1613,16090,15.0,Female,Hyderabad,COVID-19,2,199702.965333,0,2023-10-07
1729,10575,79.0,Male,Chennai,Diabetes,9,199702.965333,0,2023-11-28
1771,15342,79.0,Female,Bangalore,Diabetes,12,199702.965333,1,2023-08-31
2077,11048,77.0,Male,Chennai,Asthma,8,199702.965333,1,2023-09-30
2166,10593,44.0,Female,Delhi,COVID-19,18,199702.965333,1,2023-02-13
2210,12711,36.0,Female,Mumbai,Diabetes,15,199702.965333,0,2023-03-19
2228,18551,86.0,Male,Bangalore,Hypertension,17,199702.965333,0,2023-11-06
2382,10830,35.0,Male,Delhi,Diabetes,18,199702.965333,1,2023-04-17
2449,10204,0.0,Male,Delhi,COVID-19,12,199702.965333,0,2023-09-20
2531,12113,99.0,Male,Mumbai,Flu,8,199702.965333,1,2023-04-23
2561,13525,NaN,Male,Bangalore,COVID-19,19,199702.965333,0,2023-01-16
2694,14088,56.0,Female,Bangalore,Hypertension,8,199702.965333,0,2023-10-06
2847,17922,NaN,Female,Delhi,COVID-19,12,199702.965333,0,2023-08-01
3213,19120,95.0,Female,Chennai,Flu,2,199702.965333,0,2023-05-12
3279,10674,10.0,Female,Mumbai,Hypertension,17,199702.965333,1,2023-12-09
3361,14781,21.0,Female,Chennai,Diabetes,3,199702.965333,1,2023-10-09
3659,13197,61.0,Female,Chennai,COVID-19,10,199702.965333,1,2023-11-06
3830,18933,15.0,Female,Mumbai,Flu,9,199702.965333,1,2023-09-09
3855,10644,77.0,Male,Delhi,Hypertension,11,199702.965333,0,2023-09-15
3874,19763,86.0,Female,Delhi,Diabetes,16,199702.965333,0,2023-03-30
4060,15944,72.0,Female,Mumbai,Asthma,16,199702.965333,0,2023-02-22
4072,10857,80.0,Male,Mumbai,COVID-19,14,199702.965333,0,2023-11-05
4207,12690,76.0,Male,Hyderabad,Asthma,14,199702.965333,1,2023-05-16
4292,12430,25.0,Male,Chennai,Diabetes,11,199702.965333,0,2023-01-01
4414,18102,91.0,Male,Hyderabad,Hypertension,2,199702.965333,1,2023-08-01
4549,17545,12.0,Female,Delhi,Diabetes,13,199702.965333,0,2023-11-11
4582,16646,NaN,Male,Delhi,Flu,4,199702.965333,1,2023-02-27
4617,10896,88.0,Female,Chennai,COVID-19,3,199702.965333,1,2023-01-01
4625,11449,NaN,Female,Hyderabad,Diabetes,5,199702.965333,1,2023-03-28
4629,14117,82.0,Male,Hyderabad,Hypertension,17,199702.965333,1,2023-11-13
4656,17384,65.0,Female,Chennai,Asthma,10,199702.965333,0,2023-05-13
4740,11764,NaN,Female,Mumbai,COVID-19,15,199702.965333,0,2023-09-22
4780,10717,52.0,Female,Mumbai,Diabetes,17,199702.965333,0,2023-02-10
4831,11827,NaN,Male,Chennai,Flu,1,199702.965333,1,2023-07-02
4895,11170,1.0,Female,Bangalore,Flu,3,199702.965333,1,2023-12-06

In [18]:
# Q6(2)
len(outlier)

50

In [19]:
df["Treatment_Cost"].isnull().sum()

np.int64(494)

In [20]:
df["Treatment_Cost"].median()

24797.0

In [21]:
df["Treatment_Cost"] = df["Treatment_Cost"].fillna(df["Treatment_Cost"].median())

In [22]:
df["Treatment_Cost"].isnull().sum()

np.int64(0)

In [23]:
'''Q7. Outlier Treatment

Scenario:
The business team wants to retain all records.

Task:

Apply capping (Winsorization) on Treatment_Cost

Use 5th and 95th percentile


'''
lower_cap = 2914.6
upper_cap = 48188.1
df["Treatment_Cost"] = df["Treatment_Cost"].clip(
    lower=lower_cap,
    upper=upper_cap
)
df["Treatment_Cost"]

0       41010.0
1       12194.0
2       45086.0
3       40842.0
4        9873.0
         ...
4996    24797.0
4997     2914.6
4998    31337.0
4999    39801.0
5095    24797.0
Name: Treatment_Cost, Length: 5001, dtype: float64

In [24]:
'''Q8. Transformation

Scenario:
 Treatment cost is highly skewed.

Task:

Apply log transformation

Create a new column

Compare before vs after distribution
'''
#Q*(1)
import numpy as np
df["Log_Treatment_Cost"]= np.log1p(df["Treatment_Cost"])
#q8(2)
df[["Treatment_Cost", "Log_Treatment_Cost"]].head()

   Treatment_Cost  Log_Treatment_Cost
0         41010.0           10.621596
1         12194.0            9.408781
2         45086.0           10.716349
3         40842.0           10.617491
4          9873.0            9.197660

In [25]:
#Q8(3)
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.hist(df["Treatment_Cost"], bins=30)
plt.title("Original Treatment Cost")

plt.subplot(1, 2, 2)
plt.hist(df["Log_Treatment_Cost"], bins=30)
plt.title("Log-Transformed Treatment Cost")

plt.tight_layout()
plt.show()

NameError: name 'plt' is not defined

In [40]:
'''9. Time-Based Missing Handling

Scenario:
 Admission dates should follow a logical sequence.

Task:

Sort data by Admission_Date

Apply forward fill or backward fill where appropriate

Justify your choice
'''
#Q9(1)
df["Admission_Date"] = pd.to_datetime(df["Admission_Date"])

df = df.sort_values("Admission_Date")
df

,Patient_ID,Age,Gender,City,Diagnosis,Hospital_Visits,Treatment_Cost,Insurance_Coverage,Admission_Date
2702,17230,41.0,Male,Bangalore,Hypertension,18,12398.000000,0,2023-01-01
866,15966,49.0,Female,Mumbai,Hypertension,10,43720.000000,1,2023-01-01
2624,16450,57.0,Female,Chennai,Diabetes,15,39718.000000,0,2023-01-01
1791,14612,94.0,Male,Delhi,Hypertension,14,23388.000000,0,2023-01-01
4292,12430,25.0,Male,Chennai,Diabetes,11,199702.965333,0,2023-01-01
...,...,...,...,...,...,...,...,...,...
265,10956,82.0,Male,Chennai,Hypertension,9,7513.000000,0,2023-12-31
3133,11238,24.0,Male,Hyderabad,Asthma,2,9847.000000,0,2023-12-31
3456,19171,NaN,Female,Mumbai,Flu,1,NaN,1,2023-12-31
4744,12671,20.0,Female,Mumbai,COVID-19,8,22863.000000,1,2023-12-31
1723,13432,NaN,Male,Bangalore,Hypertension,9,NaN,1,2023-12-31

In [41]:
#q9(2)
df["Admission_Date"].isnull().sum()
#No missing values were found in Admission_Date, so forward fill or backward fill was not required.

np.int64(0)